import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout";
import { useState } from "react";
import EmojiList from "../components/EmojiList";
import emojisData from "../data/emojis";
import CategoryCard from "../components/CategoryCard";

const Home: NextPage = () => {
  const [filteredEmojis, setFilteredEmojis] = useState(emojisData.slice(0, 80));
  const [currentSearch, setCurrentSearch] = useState("");
  function filterBySearch(search: string) {
    if (search.trim().length > 0) {
      setFilteredEmojis(
        emojisData.filter((emoji) =>
          emoji.name.toUpperCase().includes(search.toUpperCase().trim())
        )
      );
    } else {
      setFilteredEmojis(emojisData.slice(0, 80));
    }
  }
  function FilterByCategory(category: string) {
    setFilteredEmojis(
      emojisData.filter((emoji) =>
        emoji.group.toUpperCase().includes(category.toUpperCase())
      )
    );
  }

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-2xl md:text-5xl font-bold text-gray-600 text-center tracking-wide">
        Welcome to <span className="text-amber-500">Infoji</span>
      </h1>
      <div className="flex justify-center">
        <input
          className="w-full max-w-xl border border-gray-300 p-3 rounded-md my-8 bg-white shadow-md focus:outline-none focus:border-cyan-500 focus:ring-1"
          id="name"
          type="text"
          placeholder="Search for an emoji"
          onChange={(e) => filterBySearch(e.target.value)}
        />
      </div>
      {currentSearch.length === 0 && (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mb-8">
          <CategoryCard
            handleFilter={FilterByCategory}
            emoji="😀"
            group={"Smileys & Emotion"}
          />
          <CategoryCard
            handleFilter={FilterByCategory}
            emoji="👨🏻"
            group={"People & Body"}
          />
          <CategoryCard
            handleFilter={FilterByCategory}
            emoji="🐶"
            group={"Animals & Nature"}
          />
          <CategoryCard
            handleFilter={FilterByCategory}
            emoji="🍔"
            group={"Food & Drink"}
          />
          <CategoryCard
            handleFilter={FilterByCategory}
            emoji="⚽️"
            group="Activities"
          />
          <CategoryCard
            handleFilter={FilterByCategory}
            emoji="🏨"
            group={"Travel & Places"}
          />
          <CategoryCard
            handleFilter={FilterByCategory}
            emoji="💡"
            group="Objects"
          />
          <CategoryCard
            handleFilter={FilterByCategory}
            emoji="⚛️"
            group="Symbols"
          />
          <CategoryCard
            handleFilter={FilterByCategory}
            emoji="🚩"
            group="Flags"
          />
        </div>
      )}
      {!filteredEmojis.length && (
        <p className="text-center text-xl text-gray-500">{`Sorry, we could'n find an emoji with: "${currentSearch}"`}</p>
      )}
      <EmojiList emojis={filteredEmojis.slice(0, 80)} />
    </Layout>
  );
};

export default Home;
